alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l.='ls -d .* --color=auto'
alias ll ='ls -alF'
alias ls='ls --color=auto'
alias sudo='usr/bin/sudo'
alias vi='vim'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'

alias black='black --line-length=120'
alias pip='pip3'
alias python='python3'
alias tmux='TERM=xterm-256color tmux'

alias sshfix='eval $(ssh-agent);ssh-add'
alias gd='git diff'
alias gds='git diff --staged'
alias gs='git status'
alias ga='git add'
alias gr='git restore'
alias grs='git restore --staged'
alias gcm='git commit -m'
alias gc='git commit'
alias gbdates='git for-each-ref --sort=committerdate refs/heads/ --format="%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:short)%(color:reset))"'
alias gco='git checkout'
alias gca='git commit --amend --no-edit --date=now'

